name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy_job:

    runs-on: ubuntu-latest
    name: build&deploy

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build:ci --if-present

    - name: Tests
      run: npm test

    - name: Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.1
      with:
        username: demo-site
        server: '${{ secrets.SERVER_IP }}'
        port: '${{ secrets.SERVER_PORT }}'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: './dist/*'
        remote_path: '/home/site/vitprog/demo-store--mock-api'
        args: '-o ConnectTimeout=5'
