name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy_job:

    runs-on: ubuntu-latest
    name: build&deploy

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build:ci --if-present

    - name: Tests
      run: npm test

    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: '${{ secrets.SERVER_IP }}'
        REMOTE_PORT: '${{ secrets.SERVER_PORT }}'
        REMOTE_USER: '${{ secrets.SERVER_USERNAME }}'
        TARGET: '${{ secrets.SERVER_PATH }}'
        EXCLUDE: 'dist/ node_modules/'
        ARGS: "-rltgoDzvO --delete"

    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        script: whoami |
          cd ${{ secrets.SERVER_PATH }} |
          npm ci |
          npm run build:ci |
          ls -l
